### ISSUE TITLE
make checks configurable

### ISSUE THREAD

**Issue by rndmh3ro** [shortdudey123/yamllint#21]
I'd like to specify which kind of error-checks are performed, e.g. test everything except duplicate key checks.

**Comment by shortdudey123** [comment]
Any reason to disable the duplicate key checking?

Duplicate keys are not allowed in the YAML specification:
`JSON's RFC4627 requires that mappings keys merely “SHOULD” be unique, while YAML insists they “MUST” be. Technically, YAML therefore complies with the JSON spec, choosing to treat duplicates as an error.`
`In practice, since JSON is silent on the semantics of such duplicates, the only portable JSON files are those with unique keys, which are therefore valid YAML files.` 
~ Section 1.3 http://www.yaml.org/spec/1.2/spec.html

**Comment by rndmh3ro** [comment]
Hiera allows merging yaml hashes, so two hashes in one file are possible (and will be merged into one).

Also flexibility in testing specific errors is alwas helpful.

**Comment by shortdudey123** [comment]
Hiera passes the yaml config file to `YAML.load_file` which does not merge duplicate keys and overrides silently.  See https://github.com/puppetlabs/hiera/blob/master/lib/hiera/config.rb#L69

All of the tests performed by this gem validate the YAML file is valid so i am not sure i see why certain tests should be disabled.  File extension check already be disabled or customized.  The other checks (not an empty file, valid syntax, and not overlapping keys) are not customizable or disableable.

However, I could see disabling the empty file check if other libraries allow empty yaml files to be loaded (psych, the default yaml library for ruby, does not).

**Comment by rndmh3ro** [comment]
Thanks for the clarification! I now think you're right! We can close this ticket.

**Comment by shortdudey123** [comment]
No problem :)
